export default {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - s",
        totalResults: "40690000000",
        searchTerms: "s",
        count: 10,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "82f40d4a9c6f64fc9",
      },
    ],
    nextPage: [
      {
        title: "Google Custom Search - s",
        totalResults: "40690000000",
        searchTerms: "s",
        count: 10,
        startIndex: 11,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "82f40d4a9c6f64fc9",
      },
    ],
  },
  context: {
    title: "Google",
  },
  searchInformation: {
    searchTime: 0.532431,
    formattedSearchTime: "0.53",
    totalResults: "40690000000",
    formattedTotalResults: "40,690,000,000",
  },
  items: [
    {
      kind: "customsearch#result",
      title:
        "Astrid S - It´s Ok If You Forget Me (Official Lyric Video) - YouTube",
      htmlTitle:
        "Astrid <b>S</b> - It´<b>s</b> Ok If You Forget Me (Official Lyric Video) - YouTube",
      link: "https://www.youtube.com/watch?v=yYchF3OLkm4",
      displayLink: "www.youtube.com",
      snippet:
        "Sep 17, 2020 ... Astrid S - It´s Ok If You Forget Me (Official Lyric Video)Listen to “- It´s Ok If You Forget Me”: https://AstridS.lnk.to/IOIYFM Connect with ...",
      htmlSnippet:
        "Sep 17, 2020 <b>...</b> Astrid <b>S</b> - It´<b>s</b> Ok If You Forget Me (Official Lyric Video)Listen to “- It´<b>s</b> Ok If You Forget Me”: https://AstridS.lnk.to/IOIYFM Connect with&nbsp;...",
      formattedUrl: "https://www.youtube.com/watch?v=yYchF3OLkm4",
      htmlFormattedUrl: "https://www.youtube.com/watch?v=yYchF3OLkm4",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrHe0zAgsZOsVEPF486pek6uj9M2E5Ptl0eGD4ZsnWnBbUPEb2HaRFdfY",
            width: "300",
            height: "168",
          },
        ],
        imageobject: [
          {
            width: "1280",
            url: "https://i.ytimg.com/vi/yYchF3OLkm4/maxresdefault.jpg",
            height: "720",
          },
        ],
        person: [
          {
            name: "AstridSofficialVEVO",
            url: "http://www.youtube.com/user/AstridSofficialVEVO",
          },
        ],
        metatags: [
          {
            "og:image": "https://i.ytimg.com/vi/yYchF3OLkm4/maxresdefault.jpg",
            "theme-color": "rgba(255, 255, 255, 0.98)",
            "og:image:width": "1280",
            "og:type": "video.other",
            "og:site_name": "YouTube",
            "al:ios:app_name": "YouTube",
            "og:title":
              "Astrid S - It´s Ok If You Forget Me (Official Lyric Video)",
            "og:image:height": "720",
            "al:android:package": "com.google.android.youtube",
            title: "Astrid S - It´s Ok If You Forget Me (Official Lyric Video)",
            "al:ios:url":
              "vnd.youtube://www.youtube.com/watch?v=yYchF3OLkm4&feature=applinks",
            "al:web:url":
              "http://www.youtube.com/watch?v=yYchF3OLkm4&feature=applinks",
            "og:video:secure_url": "https://www.youtube.com/embed/yYchF3OLkm4",
            "og:video:tag": "Astrid S",
            "og:description":
              "Astrid S - It´s Ok If You Forget Me (Official Lyric Video)Listen to “- It´s Ok If You Forget Me”: https://AstridS.lnk.to/IOIYFM Connect with Astrid S: https:...",
            "og:video:width": "1280",
            "al:ios:app_store_id": "544007664",
            "al:android:url":
              "vnd.youtube://www.youtube.com/watch?v=yYchF3OLkm4&feature=applinks",
            "og:video:type": "text/html",
            "og:video:height": "720",
            "og:video:url": "https://www.youtube.com/embed/yYchF3OLkm4",
            "og:url": "https://www.youtube.com/watch?v=yYchF3OLkm4",
            "al:android:app_name": "YouTube",
          },
        ],
        videoobject: [
          {
            embedurl: "https://www.youtube.com/embed/yYchF3OLkm4",
            playertype: "HTML5 Flash",
            isfamilyfriendly: "true",
            uploaddate: "2020-09-17",
            description:
              "Astrid S - It´s Ok If You Forget Me (Official Lyric Video)Listen to “- It´s Ok If You Forget Me”: https://AstridS.lnk.to/IOIYFM Connect with Astrid S: https:...",
            videoid: "yYchF3OLkm4",
            url: "https://www.youtube.com/watch?v=yYchF3OLkm4",
            duration: "PT3M29S",
            unlisted: "False",
            name: "Astrid S - It´s Ok If You Forget Me (Official Lyric Video)",
            paid: "False",
            width: "1280",
            regionsallowed:
              "AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BQ,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CU,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,EH...",
            genre: "Music",
            interactioncount: "34915503",
            channelid: "UCkZc1mlptb_EI3n9kYUGgEA",
            datepublished: "2020-09-17",
            thumbnailurl:
              "https://i.ytimg.com/vi/yYchF3OLkm4/maxresdefault.jpg",
            height: "720",
          },
        ],
        cse_image: [
          {
            src: "https://i.ytimg.com/vi/yYchF3OLkm4/maxresdefault.jpg",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "S Corporations | Internal Revenue Service",
      htmlTitle: "<b>S</b> Corporations | Internal Revenue Service",
      link: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporations",
      displayLink: "www.irs.gov",
      snippet:
        "Sep 2, 2022 ... S corporations are responsible for tax on certain built-in gains and passive income at the entity level. To qualify for S corporation status, ...",
      htmlSnippet:
        "Sep 2, 2022 <b>...</b> <b>S</b> corporations are responsible for tax on certain built-in gains and passive income at the entity level. To qualify for <b>S</b> corporation status,&nbsp;...",
      cacheId: "El-e0FYf11YJ",
      formattedUrl:
        "https://www.irs.gov/businesses/small-businesses-self.../s-corporations",
      htmlFormattedUrl:
        "https://www.irs.gov/businesses/small-businesses-self.../<b>s</b>-corporations",
      pagemap: {
        xfn: [{}],
        metatags: [
          {
            "twitter:card": "summary",
            "irsstandard-type": "NULL",
            channel: "NULL",
            "og:image:type": "image/jpeg",
            prod_seid: "SKHCB",
            "twitter:dnt": "on",
            "twitter:image": "https://www.irs.gov/pub/image/logo_small.jpg",
            "twitter:image:alt": "IRS logo",
            rights: "United States Internal Revenue Services",
            uniqueid: "17120",
            "og:image:alt": "IRS logo",
            "twitter:title": "S Corporations | Internal Revenue Service",
            audience: "NULL",
            "og:image:url": "https://www.irs.gov/pub/image/logo_small.jpg",
            handheldfriendly: "true",
            ishistorical: "no",
            abstract:
              "By electing to be treated as an S corporation, an eligible domestic corporation can avoid double taxation.",
            otid: "98263",
            viewport: "width=device-width, initial-scale=1.0",
            guidance: "NULL",
            "twitter:description":
              "S corporations are corporations that elect to pass corporate income, losses, deductions, and credits through to their shareholders for federal tax purposes. Shareholders of S corporations report the flow-through of income and losses on their personal tax returns and are assessed tax at their individual income tax rates. This allows S corporations to avoid double taxation on the corporate income. S corporations are responsible for tax on certain built-in gains and passive income at the entity level.",
            mobileoptimized: "width",
            organization: "NULL",
            "original-source":
              "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporations",
            topic: "NULL",
            "historical-date": "NULL",
            changed: "1659977756",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "『S』 (@s) / Twitter",
      htmlTitle: "『<b>S</b>』 (@<b>s</b>) / Twitter",
      link: "https://twitter.com/s",
      displayLink: "twitter.com",
      snippet:
        "Interested in @s's Tweets? Turn on account notifications to keep up with all new content. Opting out is easy, so give it a try. Allow notifications.",
      htmlSnippet:
        "Interested in @<b>s&#39;s</b> Tweets? Turn on account notifications to keep up with all new content. Opting out is easy, so give it a try. Allow notifications.",
      cacheId: "MyVsc8AEsp8J",
      formattedUrl: "https://twitter.com/s",
      htmlFormattedUrl: "https://twitter.com/<b>s</b>",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT58fNKxOg6T7SZ8Po8NmDVb-12Z61Myn8HpARxyIHUicoz7o1ps6ac5A",
            width: "48",
            height: "48",
          },
        ],
        imageobject: [
          {
            contenturl: "https://pbs.twimg.com/media/Fbw3cvIXkAMLtsc.jpg",
            width: "956",
            caption: "Image",
            thumbnailurl:
              "https://pbs.twimg.com/media/Fbw3cvIXkAMLtsc?format=jpg&name=thumb",
          },
          {
            contenturl: "https://pbs.twimg.com/media/Faoar3_WIAI3y-s.jpg",
            width: "1920",
            caption: "Image",
            thumbnailurl:
              "https://pbs.twimg.com/media/Faoar3_WIAI3y-s?format=jpg&name=thumb",
          },
          {
            contenturl: "https://pbs.twimg.com/media/FaUQf5PWYAAWUeX.jpg",
            width: "665",
            caption: "Image",
            thumbnailurl:
              "https://pbs.twimg.com/media/FaUQf5PWYAAWUeX?format=jpg&name=thumb",
          },
          {
            contenturl: "https://pbs.twimg.com/media/FPjSswVXEAYG-g0.jpg",
            width: "1170",
            caption: "Image",
            thumbnailurl:
              "https://pbs.twimg.com/media/FPjSswVXEAYG-g0?format=jpg&name=thumb",
          },
          {
            contenturl: "https://pbs.twimg.com/media/FO0sdLDXIAABUtb.jpg",
            width: "828",
            caption: "Image",
            thumbnailurl:
              "https://pbs.twimg.com/media/FO0sdLDXIAABUtb?format=jpg&name=thumb",
          },
        ],
        person: [
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
          {
            identifier: "347002675",
            givenname: "『S』",
            additionalname: "s",
          },
        ],
        interactioncounter: [
          {
            userinteractioncount: "33899",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1272299561378369536/likes",
          },
          {
            userinteractioncount: "371",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1272299561378369536/retweets",
          },
          {
            userinteractioncount: "240",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1272299561378369536/retweets/with_comments",
          },
          {
            userinteractioncount: "527",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1272299561378369536",
          },
          {
            userinteractioncount: "7",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1576637681949609984/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1576637681949609984/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1576637681949609984/retweets/with_comments",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1576637681949609984",
          },
          {
            userinteractioncount: "102",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1566486253998071808/likes",
          },
          {
            userinteractioncount: "6",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1566486253998071808/retweets",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1566486253998071808/retweets/with_comments",
          },
          {
            userinteractioncount: "12",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1566486253998071808",
          },
          {
            userinteractioncount: "49",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1566187756417650690/likes",
          },
          {
            userinteractioncount: "6",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1566187756417650690/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1566187756417650690/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1566187756417650690",
          },
          {
            userinteractioncount: "51",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1561089612793188355/likes",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1561089612793188355/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1561089612793188355/retweets/with_comments",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1561089612793188355",
          },
          {
            userinteractioncount: "11",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1559670993114873862/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1559670993114873862/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1559670993114873862/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1559670993114873862",
          },
          {
            userinteractioncount: "36",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1559384685087801345/likes",
          },
          {
            userinteractioncount: "7",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1559384685087801345/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1559384685087801345/retweets/with_comments",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1559384685087801345",
          },
          {
            userinteractioncount: "18",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1558923030436499458/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1558923030436499458/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1558923030436499458/retweets/with_comments",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1558923030436499458",
          },
          {
            userinteractioncount: "43",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1556715549698265089/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1556715549698265089/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1556715549698265089/retweets/with_comments",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1556715549698265089",
          },
          {
            userinteractioncount: "17",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1556040546279366661/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1556040546279366661/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1556040546279366661/retweets/with_comments",
          },
          {
            userinteractioncount: "7",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1556040546279366661",
          },
          {
            userinteractioncount: "16",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1547207916477751297/likes",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1547207916477751297/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1547207916477751297/retweets/with_comments",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1547207916477751297",
          },
          {
            userinteractioncount: "22",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1544735739933560833/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1544735739933560833/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1544735739933560833/retweets/with_comments",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1544735739933560833",
          },
          {
            userinteractioncount: "23",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1543552048498704384/likes",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1543552048498704384/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1543552048498704384/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1543552048498704384",
          },
          {
            userinteractioncount: "10",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1539343641738625026/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1539343641738625026/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1539343641738625026/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1539343641738625026",
          },
          {
            userinteractioncount: "11",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1539343640874590210/likes",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1539343640874590210/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1539343640874590210/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1539343640874590210",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1539343640052604928/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1539343640052604928/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1539343640052604928/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1539343640052604928",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1539343639226339329/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1539343639226339329/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1539343639226339329/retweets/with_comments",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1539343639226339329",
          },
          {
            userinteractioncount: "15",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1539343637791784968/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1539343637791784968/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1539343637791784968/retweets/with_comments",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1539343637791784968",
          },
          {
            userinteractioncount: "13",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1536425210454343681/likes",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1536425210454343681/retweets",
          },
          {
            userinteractioncount: "7",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1536425210454343681/retweets/with_comments",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1536425210454343681",
          },
          {
            userinteractioncount: "25",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1533629823658123264/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1533629823658123264/retweets",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1533629823658123264/retweets/with_comments",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1533629823658123264",
          },
          {
            userinteractioncount: "52",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1533613155133399041/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1533613155133399041/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1533613155133399041/retweets/with_comments",
          },
          {
            userinteractioncount: "6",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1533613155133399041",
          },
          {
            userinteractioncount: "8",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1533552240547581956/likes",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1533552240547581956/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1533552240547581956/retweets/with_comments",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1533552240547581956",
          },
          {
            userinteractioncount: "14",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1533473041686188032/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1533473041686188032/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1533473041686188032/retweets/with_comments",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1533473041686188032",
          },
          {
            userinteractioncount: "24",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1533192327107321857/likes",
          },
          {
            userinteractioncount: "6",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1533192327107321857/retweets",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1533192327107321857/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1533192327107321857",
          },
          {
            userinteractioncount: "8",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1532928481906110465/likes",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1532928481906110465/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1532928481906110465/retweets/with_comments",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1532928481906110465",
          },
          {
            userinteractioncount: "34",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1532128253523156993/likes",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1532128253523156993/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1532128253523156993/retweets/with_comments",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1532128253523156993",
          },
          {
            userinteractioncount: "21",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1522802596565630977/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1522802596565630977/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1522802596565630977/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1522802596565630977",
          },
          {
            userinteractioncount: "46",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1511189347369947138/likes",
          },
          {
            userinteractioncount: "6",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1511189347369947138/retweets",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1511189347369947138/retweets/with_comments",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1511189347369947138",
          },
          {
            userinteractioncount: "20",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1510765703376347141/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1510765703376347141/retweets",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1510765703376347141/retweets/with_comments",
          },
          {
            userinteractioncount: "7",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1510765703376347141",
          },
          {
            userinteractioncount: "56",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1507910332664233990/likes",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1507910332664233990/retweets",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1507910332664233990/retweets/with_comments",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1507910332664233990",
          },
          {
            userinteractioncount: "28",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1507890492461170693/likes",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1507890492461170693/retweets",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1507890492461170693/retweets/with_comments",
          },
          {
            userinteractioncount: "17",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1507890492461170693",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1507817507129683969/likes",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1507817507129683969/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1507817507129683969/retweets/with_comments",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1507817507129683969",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1507776245123100673/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1507776245123100673/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1507776245123100673/retweets/with_comments",
          },
          {
            userinteractioncount: "3",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1507776245123100673",
          },
          {
            userinteractioncount: "30",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1495935049459503108/likes",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1495935049459503108/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1495935049459503108/retweets/with_comments",
          },
          {
            userinteractioncount: "17",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1495935049459503108",
          },
          {
            userinteractioncount: "44",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1495922322271789056/likes",
          },
          {
            userinteractioncount: "6",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1495922322271789056/retweets",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1495922322271789056/retweets/with_comments",
          },
          {
            userinteractioncount: "150",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1495922322271789056",
          },
          {
            userinteractioncount: "26",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1494010019288858625/likes",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1494010019288858625/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1494010019288858625/retweets/with_comments",
          },
          {
            userinteractioncount: "2",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1494010019288858625",
          },
          {
            userinteractioncount: "11",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1493944638352338944/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1493944638352338944/retweets",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1493944638352338944/retweets/with_comments",
          },
          {
            userinteractioncount: "4",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1493944638352338944",
          },
          {
            userinteractioncount: "15",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1493802466307190786/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1493802466307190786/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1493802466307190786/retweets/with_comments",
          },
          {
            userinteractioncount: "18",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1493802466307190786",
          },
          {
            userinteractioncount: "9",
            interactiontype: "https://schema.org/LikeAction",
            name: "Likes",
            url: "https://twitter.com/s/status/1493772682948755457/likes",
          },
          {
            userinteractioncount: "0",
            interactiontype: "https://schema.org/InteractAction",
            name: "Retweets",
            url: "https://twitter.com/s/status/1493772682948755457/retweets",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Quotes",
            url: "https://twitter.com/s/status/1493772682948755457/retweets/with_comments",
          },
          {
            userinteractioncount: "1",
            interactiontype: "https://schema.org/InteractAction",
            name: "Replies",
            url: "https://twitter.com/s/status/1493772682948755457",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://pbs.twimg.com/profile_images/1493773422354075656/LIy3QnyA_normal.jpg",
            "theme-color": "#ffffff",
            "og:type": "profile",
            "og:site_name": "Twitter",
            "al:ios:app_name": "Twitter",
            "apple-mobile-web-app-title": "Twitter",
            "og:title": "『S』 (@s) / Twitter",
            "al:android:package": "com.twitter.android",
            "al:ios:url": "twitter://user?screen_name=s",
            "og:description": "📬 youresus@protonmail.com",
            "al:ios:app_store_id": "333903271",
            "facebook-domain-verification": "x6sdcc8b5ju3bh8nbm59eswogvg6t1",
            "al:android:url": "twitter://user?screen_name=s",
            "fb:app_id": "2231777543",
            "apple-mobile-web-app-status-bar-style": "white",
            viewport:
              "width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover",
            "mobile-web-app-capable": "yes",
            "og:url": "https://twitter.com/s",
            "al:android:app_name": "Twitter",
          },
        ],
        videoobject: [
          {
            duration: "PT0H0M0S",
            embedurl:
              "https://platform.twitter.com/embed/Tweet.html?dnt=false&embedId=twitter-widget-1&frame=false&hideCard=false&hideThread=false&lang=en&id=1522802596565630977",
            contenturl:
              "https://video.twimg.com/tweet_video/FSIU42VWQAAkOJG.mp4",
            uploaddate: "2022-05-07T04:56:45.000Z",
            name: "@s's video Tweet",
            description: "Tgif Dance GIF",
            caption: "Tgif Dance GIF",
            thumbnailurl:
              "https://pbs.twimg.com/tweet_video_thumb/FSIU42VWQAAkOJG.jpg",
          },
        ],
        collection: [
          {
            name: "Profile Tweets",
          },
        ],
        creativework: [
          {
            name: "Expanded Tweet URLs",
            url: "https://t.co/1ms5cnedb8",
          },
          {
            name: "Expanded Tweet URLs",
            url: "https://t.co/A0uVVWknyl",
          },
          {
            name: "Expanded Tweet URLs",
            url: "https://t.co/qpyLRHnF9U",
          },
          {
            name: "Expanded Tweet URLs",
            url: "https://t.co/g9oUBiKsQK",
          },
          {
            name: "Expanded Tweet URLs",
            url: "https://t.co/IvJUtIYphk",
          },
          {
            name: "Expanded Tweet URLs",
            url: "https://t.co/4SirLlJLRY",
          },
        ],
        cse_image: [
          {
            src: "https://pbs.twimg.com/profile_images/1493773422354075656/LIy3QnyA_normal.jpg",
          },
        ],
        socialmediaposting: [
          {
            identifier: "1272299561378369536",
            commentcount: "527",
            articlebody: "Like this if you found this account by mistake 👀",
            position: "1",
            datecreated: "2020-06-14T22:47:08.000Z",
            datepublished: "2020-06-14T22:47:08.000Z",
            url: "https://twitter.com/s/status/1272299561378369536",
          },
          {
            identifier: "1576637681949609984",
            commentcount: "0",
            articlebody:
              "Fantasy football is 99% luck You can't convince me otherwise",
            position: "2",
            datecreated: "2022-10-02T18:18:10.000Z",
            datepublished: "2022-10-02T18:18:10.000Z",
            url: "https://twitter.com/s/status/1576637681949609984",
          },
          {
            identifier: "1566486253998071808",
            commentcount: "12",
            articlebody: "S",
            position: "3",
            datecreated: "2022-09-04T18:00:01.000Z",
            datepublished: "2022-09-04T18:00:01.000Z",
            url: "https://twitter.com/s/status/1566486253998071808",
          },
          {
            identifier: "1566187756417650690",
            commentcount: "2",
            articlebody:
              "Somewhere out there I bet there's a guy who bought Bitcoin at $64k and has a garage full of unsold fidget spinners",
            position: "4",
            datecreated: "2022-09-03T22:13:54.000Z",
            datepublished: "2022-09-03T22:13:54.000Z",
            url: "https://twitter.com/s/status/1566187756417650690",
          },
          {
            identifier: "1561089612793188355",
            commentcount: "3",
            articlebody: "Today is #MyTwitterAnniversary",
            position: "5",
            datecreated: "2022-08-20T20:35:41.000Z",
            datepublished: "2022-08-20T20:35:41.000Z",
            url: "https://twitter.com/s/status/1561089612793188355",
          },
          {
            identifier: "1559670993114873862",
            commentcount: "2",
            articlebody:
              "This guy Do Kwon pitched this really cool new algorithmic stablecoin. It's going to change crypto forever. Apparently, his first version had some hiccups, but the founder ironed out the issues....",
            position: "6",
            datecreated: "2022-08-16T22:38:36.000Z",
            datepublished: "2022-08-16T22:38:36.000Z",
            url: "https://twitter.com/s/status/1559670993114873862",
          },
          {
            identifier: "1559384685087801345",
            commentcount: "0",
            articlebody: "if life is a party, i'm the piñata",
            position: "7",
            datecreated: "2022-08-16T03:40:55.000Z",
            datepublished: "2022-08-16T03:40:55.000Z",
            url: "https://twitter.com/s/status/1559384685087801345",
          },
          {
            identifier: "1558923030436499458",
            commentcount: "3",
            articlebody:
              "Men used to go to war, now they tweet about the ETH merge",
            position: "8",
            datecreated: "2022-08-14T21:06:28.000Z",
            datepublished: "2022-08-14T21:06:28.000Z",
            url: "https://twitter.com/s/status/1558923030436499458",
          },
          {
            identifier: "1556715549698265089",
            commentcount: "3",
            articlebody:
              "By age 30, you should have: -Made your first million in crypto -Lost your last million crypto -does anyone have a couch I can sleep on tonight?",
            position: "9",
            datecreated: "2022-08-08T18:54:44.000Z",
            datepublished: "2022-08-08T18:54:44.000Z",
            url: "https://twitter.com/s/status/1556715549698265089",
          },
          {
            identifier: "1556040546279366661",
            commentcount: "7",
            articlebody: "Meatball pizza is underrated.",
            position: "10",
            datecreated: "2022-08-06T22:12:30.000Z",
            datepublished: "2022-08-06T22:12:30.000Z",
            url: "https://twitter.com/s/status/1556040546279366661",
          },
          {
            identifier: "1547207916477751297",
            commentcount: "1",
            articlebody:
              "Apple's M2 chip is cool, but call me when it can support the messages app without crashing.",
            position: "11",
            datecreated: "2022-07-13T13:14:47.000Z",
            datepublished: "2022-07-13T13:14:47.000Z",
            url: "https://twitter.com/s/status/1547207916477751297",
          },
          {
            identifier: "1544735739933560833",
            commentcount: "4",
            articlebody: "You guys hear that thing about politics?",
            position: "12",
            datecreated: "2022-07-06T17:31:14.000Z",
            datepublished: "2022-07-06T17:31:14.000Z",
            url: "https://twitter.com/s/status/1544735739933560833",
          },
          {
            identifier: "1543552048498704384",
            commentcount: "2",
            articlebody: "How do you do fellow kids?",
            position: "13",
            datecreated: "2022-07-03T11:07:40.000Z",
            datepublished: "2022-07-03T11:07:40.000Z",
            url: "https://twitter.com/s/status/1543552048498704384",
          },
          {
            identifier: "1539343641738625026",
            commentcount: "2",
            articlebody:
              "Finally, remember that this too shall pass! Bear markets don't last forever, and eventually the market will recover.",
            ispartof: "https://twitter.com/s/status/1539343640874590210",
            position: "14",
            datecreated: "2022-06-21T20:24:58.000Z",
            datepublished: "2022-06-21T20:24:58.000Z",
            url: "https://twitter.com/s/status/1539343641738625026",
          },
          {
            identifier: "1539343640874590210",
            commentcount: "2",
            articlebody:
              "Third: have a plan. Know how much you're willing to lose and stick to it.",
            ispartof: "https://twitter.com/s/status/1539343640052604928",
            position: "15",
            datecreated: "2022-06-21T20:24:58.000Z",
            datepublished: "2022-06-21T20:24:58.000Z",
            url: "https://twitter.com/s/status/1539343640874590210",
          },
          {
            identifier: "1539343640052604928",
            commentcount: "2",
            articlebody:
              "Second: don't try to time the market. Trying to predict when it will bottom out is a fool's errand.",
            ispartof: "https://twitter.com/s/status/1539343639226339329",
            position: "16",
            datecreated: "2022-06-21T20:24:58.000Z",
            datepublished: "2022-06-21T20:24:58.000Z",
            url: "https://twitter.com/s/status/1539343640052604928",
          },
          {
            identifier: "1539343639226339329",
            commentcount: "1",
            articlebody:
              "First: don't panic. Remember that markets go up and down, and this is just a normal part of the cycle.",
            ispartof: "https://twitter.com/s/status/1539343637791784968",
            position: "17",
            datecreated: "2022-06-21T20:24:57.000Z",
            datepublished: "2022-06-21T20:24:57.000Z",
            url: "https://twitter.com/s/status/1539343639226339329",
          },
          {
            identifier: "1539343637791784968",
            commentcount: "1",
            articlebody: "How to get through a bear market 🧵",
            position: "18",
            datecreated: "2022-06-21T20:24:57.000Z",
            datepublished: "2022-06-21T20:24:57.000Z",
            url: "https://twitter.com/s/status/1539343637791784968",
          },
          {
            identifier: "1536425210454343681",
            commentcount: "3",
            articlebody: "I bought 10 bitcoin today! Am I right yet?",
            position: "19",
            datecreated: "2022-06-13T19:08:10.000Z",
            datepublished: "2022-06-13T19:08:10.000Z",
            url: "https://twitter.com/s/status/1536425210454343681",
          },
          {
            identifier: "1533629823658123264",
            commentcount: "0",
            articlebody: "Wow That Steph Curry guy is really good",
            position: "20",
            datecreated: "2022-06-06T02:00:18.000Z",
            datepublished: "2022-06-06T02:00:18.000Z",
            url: "https://twitter.com/s/status/1533629823658123264",
          },
          {
            identifier: "1533613155133399041",
            commentcount: "6",
            articlebody:
              "I'm offended by all the people who liked and didn't follow 😤",
            ispartof: "https://twitter.com/s/status/1272299561378369536",
            position: "21",
            datecreated: "2022-06-06T00:54:03.000Z",
            datepublished: "2022-06-06T00:54:03.000Z",
            url: "https://twitter.com/s/status/1533613155133399041",
          },
          {
            identifier: "1533552240547581956",
            commentcount: "0",
            articlebody: "All upsets are just mismatched expectations",
            position: "22",
            datecreated: "2022-06-05T20:52:00.000Z",
            datepublished: "2022-06-05T20:52:00.000Z",
            url: "https://twitter.com/s/status/1533552240547581956",
          },
          {
            identifier: "1533473041686188032",
            commentcount: "0",
            articlebody:
              "A bad economy doesn’t create financial problems, it reveals them.",
            position: "23",
            datecreated: "2022-06-05T15:37:18.000Z",
            datepublished: "2022-06-05T15:37:18.000Z",
            url: "https://twitter.com/s/status/1533473041686188032",
          },
          {
            identifier: "1533192327107321857",
            commentcount: "2",
            articlebody: "Nothing changes, if nothing changes.",
            position: "24",
            datecreated: "2022-06-04T21:01:50.000Z",
            datepublished: "2022-06-04T21:01:50.000Z",
            url: "https://twitter.com/s/status/1533192327107321857",
          },
          {
            identifier: "1532928481906110465",
            commentcount: "3",
            articlebody: "Weeewoooooooo",
            position: "25",
            datecreated: "2022-06-04T03:33:25.000Z",
            datepublished: "2022-06-04T03:33:25.000Z",
            url: "https://twitter.com/s/status/1532928481906110465",
          },
          {
            identifier: "1532128253523156993",
            commentcount: "1",
            articlebody: "🤏🕶 😎",
            position: "26",
            datecreated: "2022-06-01T22:33:35.000Z",
            datepublished: "2022-06-01T22:33:35.000Z",
            url: "https://twitter.com/s/status/1532128253523156993",
          },
          {
            identifier: "1522802596565630977",
            commentcount: "2",
            position: "27",
            datecreated: "2022-05-07T04:56:45.000Z",
            datepublished: "2022-05-07T04:56:45.000Z",
            url: "https://twitter.com/s/status/1522802596565630977",
          },
          {
            identifier: "1511189347369947138",
            commentcount: "4",
            position: "28",
            datecreated: "2022-04-05T03:49:51.000Z",
            datepublished: "2022-04-05T03:49:51.000Z",
            url: "https://twitter.com/s/status/1511189347369947138",
          },
          {
            identifier: "1510765703376347141",
            commentcount: "7",
            articlebody: "Does anyone care about the #GRAMMYs anymore?",
            position: "29",
            datecreated: "2022-04-03T23:46:27.000Z",
            datepublished: "2022-04-03T23:46:27.000Z",
            url: "https://twitter.com/s/status/1510765703376347141",
          },
          {
            identifier: "1507910332664233990",
            commentcount: "4",
            articlebody: "Ya riiiite",
            position: "30",
            datecreated: "2022-03-27T02:40:13.000Z",
            datepublished: "2022-03-27T02:40:13.000Z",
            url: "https://twitter.com/s/status/1507910332664233990",
          },
          {
            identifier: "1507890492461170693",
            commentcount: "17",
            articlebody: "Who should I follow? My feed is too empty",
            position: "31",
            datecreated: "2022-03-27T01:21:23.000Z",
            datepublished: "2022-03-27T01:21:23.000Z",
            url: "https://twitter.com/s/status/1507890492461170693",
          },
          {
            identifier: "1507817507129683969",
            commentcount: "4",
            articlebody: "winning",
            ispartof: "https://twitter.com/s/status/1495922322271789056",
            position: "32",
            datecreated: "2022-03-26T20:31:22.000Z",
            datepublished: "2022-03-26T20:31:22.000Z",
            url: "https://twitter.com/s/status/1507817507129683969",
          },
          {
            identifier: "1507776245123100673",
            commentcount: "3",
            articlebody:
              "Why do sports fans get to mad in March? It's not that bad of a month!",
            position: "33",
            datecreated: "2022-03-26T17:47:24.000Z",
            datepublished: "2022-03-26T17:47:24.000Z",
            url: "https://twitter.com/s/status/1507776245123100673",
          },
          {
            identifier: "1495935049459503108",
            commentcount: "17",
            articlebody: "I'm winning",
            ispartof: "https://twitter.com/s/status/1495922322271789056",
            position: "34",
            datecreated: "2022-02-22T01:34:43.000Z",
            datepublished: "2022-02-22T01:34:43.000Z",
            url: "https://twitter.com/s/status/1495935049459503108",
          },
          {
            identifier: "1495922322271789056",
            commentcount: "150",
            articlebody: "Last person to reply wins $500",
            position: "35",
            datecreated: "2022-02-22T00:44:09.000Z",
            datepublished: "2022-02-22T00:44:09.000Z",
            url: "https://twitter.com/s/status/1495922322271789056",
          },
          {
            identifier: "1494010019288858625",
            commentcount: "2",
            articlebody:
              "Cameo added Simon Leviev (Tinder Swindler) @BookCameo you're going to donate all the proceeds to his victims, right?",
            position: "36",
            datecreated: "2022-02-16T18:05:20.000Z",
            datepublished: "2022-02-16T18:05:20.000Z",
            url: "https://twitter.com/s/status/1494010019288858625",
          },
          {
            identifier: "1493944638352338944",
            commentcount: "4",
            articlebody: "GM twitter",
            position: "37",
            datecreated: "2022-02-16T13:45:32.000Z",
            datepublished: "2022-02-16T13:45:32.000Z",
            url: "https://twitter.com/s/status/1493944638352338944",
          },
          {
            identifier: "1493802466307190786",
            commentcount: "18",
            articlebody: "what does “S” stand for?",
            position: "38",
            datecreated: "2022-02-16T04:20:36.000Z",
            datepublished: "2022-02-16T04:20:36.000Z",
            url: "https://twitter.com/s/status/1493802466307190786",
          },
          {
            identifier: "1493772682948755457",
            commentcount: "1",
            articlebody: "Curling is a such a ridiculous “sport” and I love it",
            position: "39",
            datecreated: "2022-02-16T02:22:15.000Z",
            datepublished: "2022-02-16T02:22:15.000Z",
            url: "https://twitter.com/s/status/1493772682948755457",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Sander (@s) • Instagram photos and videos",
      htmlTitle: "Sander (@<b>s</b>) • Instagram photos and videos",
      link: "https://www.instagram.com/s/?hl=en",
      displayLink: "www.instagram.com",
      snippet:
        "704k Followers, 419 Following, 386 Posts - See Instagram photos and videos from Sander (@s)",
      htmlSnippet:
        "704k Followers, 419 Following, 386 Posts - See Instagram photos and videos from Sander (@<b>s</b>)",
      formattedUrl: "https://www.instagram.com/s/?hl=en",
      htmlFormattedUrl: "https://www.instagram.com/<b>s</b>/?hl=en",
      pagemap: {
        xfn: [{}],
        metatags: [
          {
            "og:image":
              "https://scontent-atl3-1.cdninstagram.com/v/t51.2885-19/119891370_719088868646025_2610630836499644084_n.jpg?stp=dst-jpg_s150x150&_nc_ht=scontent-atl3-1.cdninstagram.com&_nc_cat=1&_nc_ohc=Cf76RJ4OMuMAX9M6hUn&edm=ABfd0MgBAAAA&ccb=7-5&oh=00_AT9u1n5mvWKypUbz2RTLmDHC425ZkY5FAHUw2G7nQOwrbw&oe=63433050&_nc_sid=7bff83",
            "theme-color": "#ffffff",
            "og:type": "profile",
            "al:ios:app_name": "Instagram",
            "og:title": "Sander (@s) • Instagram photos and videos",
            "al:android:package": "com.instagram.android",
            "al:ios:url": "instagram://user?username=s",
            "og:description":
              "704k Followers, 419 Following, 386 Posts - See Instagram photos and videos from Sander (@s)",
            "al:ios:app_store_id": "389801252",
            "al:android:url": "https://www.instagram.com/_u/s/",
            "apple-mobile-web-app-status-bar-style": "default",
            viewport:
              "width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover",
            "mobile-web-app-capable": "yes",
            "og:url": "https://www.instagram.com/s/",
            "al:android:app_name": "Instagram",
          },
        ],
        cse_image: [
          {
            src: "https://scontent-atl3-1.cdninstagram.com/v/t51.2885-19/119891370_719088868646025_2610630836499644084_n.jpg?stp=dst-jpg_s150x150&_nc_ht=scontent-atl3-1.cdninstagram.com&_nc_cat=1&_nc_ohc=Cf76RJ4OMuMAX9M6hUn&edm=ABfd0MgBAAAA&ccb=7-5&oh=00_AT9u1n5mvWKypUbz2RTLmDHC425ZkY5FAHUw2G7nQOwrbw&oe=63433050&_nc_sid=7bff83",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Model S | Tesla",
      htmlTitle: "Model <b>S</b> | Tesla",
      link: "https://www.tesla.com/models",
      displayLink: "www.tesla.com",
      snippet:
        "Model S is built for speed and range, with beyond ludicrous acceleration, unparalleled performance and a refined design.",
      htmlSnippet:
        "Model <b>S</b> is built for speed and range, with beyond ludicrous acceleration, unparalleled performance and a refined design.",
      cacheId: "Ei43u66-EP0J",
      formattedUrl: "https://www.tesla.com/models",
      htmlFormattedUrl: "https://www.tesla.com/models",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTAXhDfXFYZXJz4pF8qq4zPPWZGhPDGZlzTsKd93BNIxAWfVnrmzibYTI2S",
            width: "311",
            height: "162",
          },
        ],
        metatags: [
          {
            "msapplication-tilecolor": "#cc0000",
            "og:image":
              "https://tesla-cdn.thron.com/delivery/public/image/tesla/56cb8c41-e898-44ce-b6b7-fe9b9a05f529/bvlatuR/std/1200x628/MS-Social",
            "twitter:card": "summary_large_image",
            "twitter:title": "Model S | Tesla",
            "theme-color": "#000000",
            "og:site_name": "Tesla",
            "og:image:url":
              "https://tesla-cdn.thron.com/delivery/public/image/tesla/56cb8c41-e898-44ce-b6b7-fe9b9a05f529/bvlatuR/std/1200x628/MS-Social",
            handheldfriendly: "true",
            "twitter:url": "https://www.tesla.com/models",
            "image:alt_text": "Tesla logo in gray on white background",
            "og:title": "Model S",
            "msapplication-tileimage":
              "/themes/custom/tesla_frontend/assets/favicons/mstile-144x144.png",
            "og:description":
              "Model S is built for speed and range, with beyond ludicrous acceleration, unparalleled performance and a refined design.",
            "twitter:creator": "@tesla",
            "og:image:secure_url":
              "https://tesla-cdn.thron.com/delivery/public/image/tesla/56cb8c41-e898-44ce-b6b7-fe9b9a05f529/bvlatuR/std/1200x628/MS-Social",
            "twitter:image":
              "https://tesla-cdn.thron.com/delivery/public/image/tesla/56cb8c41-e898-44ce-b6b7-fe9b9a05f529/bvlatuR/std/1200x628/MS-Social",
            "twitter:site": "@tesla",
            "apple-mobile-web-app-status-bar-style": "black",
            viewport:
              "width=device-width, minimum-scale=1.0, initial-scale=1.0, shrink-to-fit=no, viewport-fit=cover",
            "twitter:description":
              "Model S is built for speed and range, with beyond ludicrous acceleration, unparalleled performance and a refined design.",
            "apple-mobile-web-app-capable": "yes",
            mobileoptimized: "width",
            "og:url": "https://www.tesla.com/models",
          },
        ],
        cse_image: [
          {
            src: "https://tesla-cdn.thron.com/delivery/public/image/tesla/56cb8c41-e898-44ce-b6b7-fe9b9a05f529/bvlatuR/std/1200x628/MS-Social",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "S s ſ",
      htmlTitle: "<b>S s ſ</b>",
      link: "https://en.wikipedia.org/wiki/S",
      displayLink: "en.wikipedia.org",
      snippet:
        "S, or s, is the nineteenth letter in the Modern English alphabet and the ISO basic Latin alphabet. Its name in English is ess (pronounced /ˈɛs/), ...",
      htmlSnippet:
        "<b>S</b>, or <b>s</b>, is the nineteenth letter in the Modern English alphabet and the ISO basic Latin alphabet. Its name in English is ess (pronounced /ˈɛ<b>s</b>/),&nbsp;...",
      cacheId: "N1bgCJL8UUwJ",
      formattedUrl: "https://en.wikipedia.org/wiki/S",
      htmlFormattedUrl: "https://en.wikipedia.org/wiki/<b>S</b>",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTeHbXY-fsbM7bHebl_w8Dg5TdpoROxQo6yizRIXE0LLgZWMI_-F8_rDvZu",
            width: "225",
            height: "225",
          },
        ],
        metatags: [
          {
            referrer: "origin",
            "og:image":
              "https://upload.wikimedia.org/wikipedia/commons/b/b8/S_cursiva.gif",
            "theme-color": "#eaecf0",
            "og:image:width": "1200",
            "og:type": "website",
            viewport:
              "width=device-width, initial-scale=1.0, user-scalable=yes, minimum-scale=0.25, maximum-scale=5.0",
            "og:title": "S - Wikipedia",
            "og:image:height": "1200",
            "format-detection": "telephone=no",
          },
        ],
        cse_image: [
          {
            src: "https://upload.wikimedia.org/wikipedia/commons/b/b8/S_cursiva.gif",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "'s Definition & Meaning - Merriam-Webster",
      htmlTitle: "&#39;<b>s</b> Definition &amp; Meaning - Merriam-Webster",
      link: "https://www.merriam-webster.com/dictionary/%27s",
      displayLink: "www.merriam-webster.com",
      snippet:
        "—used to form the possessive of singular nouns boy's , of plural nouns not ending in s children's , of some pronouns anyone's , and of word groups ...",
      htmlSnippet:
        "—used to form the possessive of singular nouns boy&#39;s , of plural nouns not ending in <b>s</b> children&#39;s , of some pronouns anyone&#39;s , and of word groups&nbsp;...",
      cacheId: "JPPXBZupgBIJ",
      formattedUrl: "https://www.merriam-webster.com/dictionary/%27s",
      htmlFormattedUrl: "https://www.merriam-webster.com/dictionary/%27s",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSKksTSKYwpW8It403nrjw5t1_a8pLO2PI6ImEG7uvFrNfacgiziPZgG-_O",
            width: "225",
            height: "225",
          },
        ],
        metatags: [
          {
            "msapplication-tilecolor": "#2b5797",
            "og:image":
              "https://merriam-webster.com/assets/mw/static/social-media-share/mw-logo-245x245@1x.png",
            "twitter:title": "Definition of 'S",
            "twitter:card": "summary",
            "theme-color": "#ffffff",
            "twitter:url": "https://www.merriam-webster.com/dictionary/%27s",
            "og:title": "Definition of 'S",
            "twitter:aria-text": "Share the Definition of 's on Twitter",
            "og:aria-text": "Post the Definition of 's to Facebook",
            "og:description": "is; was; has… See the full definition",
            "twitter:image":
              "https://merriam-webster.com/assets/mw/static/social-media-share/mw-logo-245x245@1x.png",
            referrer: "unsafe-url",
            "fb:app_id": "178450008855735",
            "twitter:site": "@MerriamWebster",
            viewport: "width=device-width, initial-scale=1.0",
            "twitter:description": "is; was; has… See the full definition",
            "og:url": "https://www.merriam-webster.com/dictionary/%27s",
          },
        ],
        cse_image: [
          {
            src: "https://merriam-webster.com/assets/mw/static/social-media-share/mw-logo-245x245@1x.png",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "'s - Wiktionary",
      htmlTitle: "&#39;<b>s</b> - Wiktionary",
      link: "https://en.wiktionary.org/wiki/%27s",
      displayLink: "en.wiktionary.org",
      snippet:
        "If you are a native speaker with a microphone, please record some and upload them. (For audio required quickly, visit WT:APR.) VerbEdit. 's (clitic).",
      htmlSnippet:
        "If you are a native speaker with a microphone, please record some and upload them. (For audio required quickly, visit WT:APR.) VerbEdit. &#39;<b>s</b> (clitic).",
      cacheId: "NopgBJaFDo4J",
      formattedUrl: "https://en.wiktionary.org/wiki/%27s",
      htmlFormattedUrl: "https://en.wiktionary.org/wiki/%27s",
      pagemap: {
        metatags: [
          {
            referrer: "origin",
            "theme-color": "#eaecf0",
            "og:type": "website",
            viewport:
              "width=device-width, initial-scale=1.0, user-scalable=yes, minimum-scale=0.25, maximum-scale=5.0",
            "og:title": "'s - Wiktionary",
            "format-detection": "telephone=no",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Xbox Series S | Xbox",
      htmlTitle: "Xbox Series <b>S</b> | Xbox",
      link: "https://www.xbox.com/en-US/consoles/xbox-series-s",
      displayLink: "www.xbox.com",
      snippet:
        "Xbox Series S console with Xbox Wireless Controller. XBOX SERIES S.. Simply next-gen. PLAY VIDEO.",
      htmlSnippet:
        "Xbox Series <b>S</b> console with Xbox Wireless Controller. XBOX SERIES <b>S</b>.. Simply next-gen. PLAY VIDEO.",
      formattedUrl: "https://www.xbox.com/en-US/consoles/xbox-series-s",
      htmlFormattedUrl:
        "https://www.xbox.com/en-US/consoles/xbox-series-<b>s</b>",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSz6EWGfxvi97TIfW1qDsLSrHHXOAiLaH52ujGWwvaF6kX2U6VG04IskQ",
            width: "200",
            height: "200",
          },
        ],
        organization: [
          {
            name: "Microsoft",
            logo: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
            "cat-logo":
              "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RW4ESm?ver=c63e",
            url: "Microsoft",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://compass-ssl.xbox.com/assets/cd/0d/cd0d44ad-8ef0-481f-ae1e-d8492ca1ab9a.jpg?n=XSS_Sharing_200x200.jpg",
            "og:type": "website",
            "twitter:card": "summary",
            "twitter:title": "Xbox Series S | Xbox",
            "og:site_name": "Xbox.com",
            "ms.sitesec": "xbox",
            "og:title": "Xbox Series S | Xbox",
            "og:description":
              "Introducing Xbox Series S. Experience next-gen speed and performance at a great price.",
            "ms.sitename": "Xbox",
            "twitter:site": "@xbox",
            viewport: "width=device-width, initial-scale=1",
            "twitter:description":
              "Introducing Xbox Series S. Experience next-gen speed and performance at a great price.",
            "ms.gpn": "/consoles/xbox-series-s",
            "awa-ver": "MSCC:NR",
            "og:url": "https://www.xbox.com/en-US/consoles/xbox-series-s",
          },
        ],
        cse_image: [
          {
            src: "https://compass-ssl.xbox.com/assets/cd/0d/cd0d44ad-8ef0-481f-ae1e-d8492ca1ab9a.jpg?n=XSS_Sharing_200x200.jpg",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Disaster Loan Assistance",
      htmlTitle: "Disaster Loan Assistance",
      link: "https://disasterloanassistance.sba.gov/ela/s/",
      displayLink: "disasterloanassistance.sba.gov",
      snippet:
        "The SBA offers disaster assistance in the form of low interest loans to businesses, nonprofit organizations, homeowners, and renters located in regions affected ...",
      htmlSnippet:
        "The SBA offers disaster assistance in the form of low interest loans to businesses, nonprofit organizations, homeowners, and renters located in regions affected&nbsp;...",
      cacheId: "PhpA4fmKLjsJ",
      formattedUrl: "https://disasterloanassistance.sba.gov/ela/s/",
      htmlFormattedUrl: "https://disasterloanassistance.sba.gov/ela/<b>s</b>/",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSkKDdRGwbVjIPcXQlTi8wVuAOiXgpd32z2upjR9gMg20FR0VppGupgY3g",
            width: "275",
            height: "183",
          },
        ],
        metatags: [
          {
            viewport:
              "initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0, minimal-ui",
          },
        ],
        cse_image: [
          {
            src: "https://disasterloanassistance.sba.gov/ela/file-asset/X01SearchDeclaration?v=1",
          },
        ],
      },
    },
  ],
};
